- bin/fryer.py
- bin/handlers.py
> Fixed GIF fryer, Back to production.

- bin/handlers.py
- bin/helpers.py
- bin/text.py
> Added aLt TeXt GeNeRaToR

- README.md
- bin/fryer.py
- bin/generator.py
- bin/handlers.py
- bin/helpers.py
- bin/text.py
> Minor changes + Updated command list

- bin/fryer.py
- requirements.txt
> Completely moved fryer from ImageIO to OpenCV.

- bin/handlers.py
- bin/utils/text.py
Bot now deletes trigger messages for Alt: and Vapourize: functions.
Fixes #94
> Added deleting functionality

- bin/handlers.py
- runtime.txt
Updated Runtime, Removed extra space
> Minor changes

- README.md
- bin/handlers.py
- bin/utils/text.py
- bot.py
Changes to README, added /changes command.
Fixes #99
> Changes to README, added /changes

- README.md
- bin/handlers.py
- bin/helpers.py
- bin/utils/text.py
Very minor refactoring, updated in-bot help text
> Very minor refactoring, updated in-bot help text

- .travis.yml
- Pipfile
- bin/utils/text.py
- runtime.txt
> Updated python version + help texts

- README.md
> Added travis CI badge, removed Heroku

- bin/drake.py
> Fixed drake pathing issue

- bin/drake.py
- bin/fryer.py
- bin/generator_classic.py
- bin/helpers.py
> Fixed more pathing issues + autoformat

- bin/fryer.py
> Fixed chilli caption bug

- bin/fryer.py
- bin/utils/text.py
> Updated changes text, testing bulges rn

- bin/fryer.py
- bin/utils/text.py
> Fixed bulge generation bug, bulges now lighting fasttt

- .travis.yml
- Pipfile
- runtime.txt
> Updated Python runtime version to 3.8.7

- Pipfile
> Updated requirements

- bin/cv.py
- bin/fryer.py
- bin/fryer_gif.py
- bin/fryer_image.py
- bin/generator_classic.py
- bin/helpers.py
- bin/utils/logs.py
> Logging changes + media file bugfix, fryer WIP

- bin/handlers.py
- bin/helpers.py
> More media bugfix

- bin/fryer_gif.py
> Fixed gif fryer chilli bug

- bin/fryer.py
- bin/fryer_image.py
- bin/helpers.py
> Added DEBUG level logging

- bin/utils/logs.py
> Corrected logging filename identification

- bin/fryer_gif.py
- bin/fryer_image.py
> Added debug logging for gif frying

- bin/fryer_gif.py
- bot.py
> Webhook updated to match library update
